[package]
name = "crc_ccit16_lib"
version = "1.0.0"
authors = ["Y. Bunduki <yuri.bunduki@dlr.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
